### ISSUE TITLE
Ln2 Autofill Request

### ISSUE THREAD

**Issue by nickkonidaris** [sdss/lvm#17]
Hello!

Guillermo is converging on an automated LN2 fill plan. We’re going to try it out over the next few days. The basic plan is to fill at 0800/1700. At each time we’ll need to identify the purge time and fill time. I.e. we’ll have a table like:
            Purge Time (min)       Fill time (min)
0800                      8                     4
1700                     17                     5
At the moment, we don’t seem to need to fill individual dewars more or less. At some point in the near future, we'll need to control the individual spectrographs that are filled. It seems likely that depending on ambient temperatures we’d want to change the purge time.

It would also be good for the fill code to slack a channel (e.g.[#lvmi-sbs-spec-status]) indicating that the fill went OK. It may be good, for example, to slack images of the “little prince” feature. I’m happy to help do this if you need help.

**Comment by albireox** [comment]
At least short-term, the implementation depends a lot on whether fixed purge and fill times are good enough. If they are, and they don't depend on external variables, using the NPS scripting interface would be the easiest and most robust way. If we need to adjust fill times based on some more complicated logic, then we'd need a small script (maybe run by a cronjon). Since eventually we'll want to use the thermistors to determine when to finish the purge, we may want to work on the script now and not try to use the NPS interface.

**Comment by gblancm** [comment]
Some safety ideas for final implementation:

- Supply valve should not open if cryostat pressure is above a threshold value (say 1e-3 torr?).
- Supply valve should not open if LN2 Can or CCD temperatures are above certain values, unless given an override (for cooling down warm pumped cryostats).
